const ScreenName = {
  HOME: 'HOME',
  EXERCISE_1: 'EXERCISE_1',
  EXERCISE_2: 'EXERCISE_2',
  EXERCISE_3: 'EXERCISE_3',
  EXERCISE_4: 'EXERCISE_4',
  EXERCISE_5: 'EXERCISE_5',
  EXERCISE_6: 'EXERCISE_6',
  EXERCISE_7: 'EXERCISE_7',
  EXERCISE_8: 'EXERCISE_8',
  EXERCISE_9: 'EXERCISE_9',
  EXERCISE_10: 'EXERCISE_10',
  EXERCISE_11: 'EXERCISE_11',
  EXERCISE_12: 'EXERCISE_12',
  EXERCISE_13: 'EXERCISE_13',
  EXERCISE_14: 'EXERCISE_14',
  EXERCISE_15: 'EXERCISE_15',
  EXERCISE_16: 'EXERCISE_16',
  EXERCISE_17: 'EXERCISE_17',
  EXERCISE_18: 'EXERCISE_18',
  EXERCISE_19: 'EXERCISE_19',
  EXERCISE_20: 'EXERCISE_20'
}

export default ScreenName
